services:
  myapp-main:
    image: bookapp:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/winter2026
      - spring.datasource.password=jordan1234
      - spring.datasource.username=root