spring.jpa.hibernate.ddl-auto=update
# This will change when you deploy a rds instance it ius now set up for local. Everything after :// will be a RDS endpoint/yourschemaname
spring.datasource.url=jdbc:mysql://localhost:3306/winter2026
# This will change when you deploy a rds instance it ius now set up for local username will be different unless you keep it as root
spring.datasource.username=root
# This will change when you deploy a rds instance it ius now set up for local PW will be different
spring.datasource.password=jordan1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
